name: flutter_snapsign
description: "Snap Sign"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^4.0.0
  image_picker: ^0.8.4+3
  http: ^0.13.3
  flutter_slidable: ^0.6.0
  cupertino_icons: ^1.0.6
  hand_signature: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
